[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cvre"
version = "0.2.2"
dependencies = [
  "jsonschema>=4.0"
]

[tool.setuptools]
packages = ["cvre"]

[tool.pytest.ini_options]
testpaths = ["tests"]
